label: "default"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${label}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${label}

chunking:
  name: "Semantic Chunking"
pre_retrieval:
  name: "Pre-retrieval"
retrieval:
  name: "Retrieval"
post_retrieval:
  name: "Post-retrieval"
generation:
  name: "Generation"
evaluation:
  name: "Evaluation"