label: "default"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${label}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${label}


common:
  OPENAI_API_KEY: "your openai api key"
chunking:
  strategies: 
    # - Semantic Chunking:
    #       mode: openai
    #       embedding_model: "text-embedding-3-large"
    #       custom_url: "custom_embedding_function_api_address"
    - Recursive Token Chunking:
        chunk_size: 800
        chunk_overlap: 400
    # - Fixed Token Chunking:
    #     chunk_size: 800
    #     chunk_overlap: 400
pre_retrieval:
  name: "Pre-retrieval"
retrieval:
  name: "Retrieval"
post_retrieval:
  name: "Post-retrieval"
generation:
  name: "Generation"
evaluation:
  name: "Evaluation"